export type PermissionAction = "Xem" | "Tạo" | "Sửa" | "Duyệt" | "Hủy";
export const permissionModules = ["Bán hàng & CRM", "Mua hàng", "Kho hàng", "Tài chính", "Sản xuất", "Nhân sự", "POS", "Dự án", "Báo cáo"] as const;
export type PermissionModule = typeof permissionModules[number];
export type RolePermissionMap = Record<string, Record<PermissionModule, PermissionAction[]>>;
export type AccountStatus = "active" | "suspended" | "invited";
const key = "mbwnext_role_permissions";
const usersKey = "mbwnext_user_access";
const activeUserKey = "mbwnext_active_user";
const persistedActiveUserKey = "mbwnext_persisted_active_user";
export type UserAccess = { name: string; email: string; role: string; scope: string; employeeId?: string; accountStatus?: AccountStatus };
const defaultUsers: UserAccess[] = [{ name: "Nguyễn Hoàng Ngọc", email: "ngoc.nguyen@example.vn", role: "System Admin", scope: "Tất cả chi nhánh", accountStatus: "active" }, { name: "Trần Minh Anh", email: "sales@anphuviet.vn", role: "Kinh doanh & CRM", scope: "Hồ Chí Minh", employeeId: "emp-002", accountStatus: "active" }, { name: "Nguyễn Thanh Bình", email: "purchase@anphuviet.vn", role: "Mua hàng", scope: "Hồ Chí Minh", employeeId: "emp-006", accountStatus: "active" }, { name: "Lê Quốc Huy", email: "warehouse@anphuviet.vn", role: "Thủ kho", scope: "Kho HCM-MAIN, HCM-RM", employeeId: "emp-003", accountStatus: "active" }, { name: "Phạm Mai Lan", email: "finance@anphuviet.vn", role: "Kế toán – Tài chính", scope: "Tất cả chi nhánh", employeeId: "emp-007", accountStatus: "active" }, { name: "Phạm Thu Hà", email: "hr@anphuviet.vn", role: "HR / Quản lý nhân sự", scope: "Phòng ban nhân sự", employeeId: "emp-004", accountStatus: "active" }, { name: "Võ Đức Long", email: "cashier@anphuviet.vn", role: "Thu ngân", scope: "Cửa hàng Quận 1", employeeId: "emp-008", accountStatus: "active" }, { name: "Nguyễn Đức Thành", email: "employee@anphuviet.vn", role: "Nhân viên", scope: "Hồ Chí Minh", employeeId: "emp-005", accountStatus: "active" }];
const rolePermissions = (visible: PermissionModule[], actions: PermissionAction[] = ["Xem", "Tạo", "Sửa"]) => Object.fromEntries(permissionModules.map((module) => [module, visible.includes(module) ? actions : []])) as Record<PermissionModule, PermissionAction[]>;
export function defaultPermissions(): RolePermissionMap { const all = Object.fromEntries(permissionModules.map((module) => [module, ["Xem", "Tạo", "Sửa", "Duyệt", "Hủy"]])); return { "System Admin": all as Record<PermissionModule, PermissionAction[]>, "Kinh doanh & CRM": rolePermissions(["Bán hàng & CRM", "Báo cáo"], ["Xem", "Tạo", "Sửa"]), "Mua hàng": rolePermissions(["Mua hàng", "Kho hàng", "Báo cáo"], ["Xem", "Tạo", "Sửa"]), "Thủ kho": rolePermissions(["Kho hàng", "Sản xuất", "Báo cáo"], ["Xem", "Tạo", "Sửa"]), "Kế toán – Tài chính": rolePermissions(["Tài chính", "Bán hàng & CRM", "Mua hàng", "Báo cáo"], ["Xem", "Tạo", "Sửa", "Duyệt"]), "HR / Quản lý nhân sự": rolePermissions(["Nhân sự", "Báo cáo"], ["Xem", "Tạo", "Sửa", "Duyệt"]), "Thu ngân": rolePermissions(["POS"], ["Xem", "Tạo", "Duyệt"]), "Nhân viên": rolePermissions(["Nhân sự"], ["Xem", "Tạo"]) }; }
export function readPermissions() { try { const stored = JSON.parse(window.sessionStorage.getItem(key) ?? "null") as RolePermissionMap | null; return { ...defaultPermissions(), ...(stored ?? {}) }; } catch { return defaultPermissions(); } }
export function writePermissions(value: RolePermissionMap) { window.sessionStorage.setItem(key, JSON.stringify(value)); }
export function can(role: string, module: PermissionModule, action: PermissionAction) { return (readPermissions()[role]?.[module] ?? []).includes(action); }
export function activeRole() { return window.sessionStorage.getItem("mbwnext_active_role") ?? activeUser()?.role ?? "System Admin"; }
export function setActiveRole(role: string) { window.sessionStorage.setItem("mbwnext_active_role", role); }
export function setActiveUser(user: UserAccess) { const value = JSON.stringify(user); window.sessionStorage.setItem(activeUserKey, value); window.localStorage.setItem(persistedActiveUserKey, value); setActiveRole(user.role); }
export function activeUser() { try { return JSON.parse(window.sessionStorage.getItem(activeUserKey) ?? window.localStorage.getItem(persistedActiveUserKey) ?? "null") as UserAccess | null; } catch { return null; } }
export function activeEmployeeId() { const user = activeUser(); const linkedEmployeeId = user?.employeeId ?? (user ? readUsers().find((item) => item.email === user.email)?.employeeId : undefined); if (linkedEmployeeId) return linkedEmployeeId; const simulatedRole = activeRole(); return user?.role === simulatedRole ? undefined : readUsers().find((item) => item.role === simulatedRole && item.accountStatus === "active")?.employeeId; }
export function isSelfServiceOnly() { return Boolean(activeEmployeeId()) && !can(activeRole(), "Nhân sự", "Duyệt"); }
export function activeScope() { const user = activeUser(); const simulatedRole = activeRole(); if (user?.role === simulatedRole) return user.scope; const simulatedUser = readUsers().find((item) => item.role === simulatedRole && item.accountStatus === "active"); return simulatedUser?.scope ?? user?.scope ?? "Tất cả chi nhánh"; }
export function isSystemAdministrator() { const user = activeUser(); return user ? user.role === "System Admin" : activeRole() === "System Admin"; }
export function resetActiveRole() { window.sessionStorage.removeItem("mbwnext_active_role"); window.sessionStorage.removeItem(activeUserKey); window.localStorage.removeItem(persistedActiveUserKey); }
const normalizeUser = (user: UserAccess): UserAccess => ({ ...user, accountStatus: user.accountStatus ?? (defaultUsers.some((seed) => seed.email === user.email) ? "active" : "invited") });
export function readUsers() { try { const stored = JSON.parse(window.sessionStorage.getItem(usersKey) ?? "null") as UserAccess[] | null; if (!stored) return defaultUsers; const storedByEmail = new Map(stored.map((user) => [user.email, normalizeUser(user)])); return [...defaultUsers.map((user) => ({ ...user, ...(storedByEmail.get(user.email) ?? {}) })), ...stored.filter((user) => !defaultUsers.some((seed) => seed.email === user.email)).map(normalizeUser)]; } catch { return defaultUsers; } }
export function writeUsers(users: UserAccess[]) { window.sessionStorage.setItem(usersKey, JSON.stringify(users)); }
export function canAccessWarehouse(warehouseCode: string) { const scope = activeScope(); if (scope === "Tất cả chi nhánh" || scope === "Phòng ban nhân sự") return true; if (scope === "Hồ Chí Minh") return warehouseCode.startsWith("HCM"); if (scope.includes("HCM-MAIN") || scope.includes("HCM-RM")) return scope.split(",").some((code) => warehouseCode === code.trim()); if (scope === "Cửa hàng Quận 1") return warehouseCode === "HCM-MAIN"; return false; }
