import { useCallback, useEffect, useState } from "react";
import { Modal } from "../../components/ui/Modal";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { useToast } from "../../components/ui/Toast";
import { activeRole, activeUser, isSystemAdministrator } from "../../lib/accessControl";
import { EmployeeSelfServiceOverview, LeaveRequest, mockApi } from "../../lib/mockApi";
import { AttendanceCalendar, personalCalendarEvents } from "./AttendanceCalendar";

const formatDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("vi-VN");
const dateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const addDays = (value: string, days: number) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + days); return dateKey(date); };

export function EmployeeSelfServicePage() {
  const user = activeUser(); const systemAdmin = isSystemAdministrator();
  const [overview, setOverview] = useState<EmployeeSelfServiceOverview | null | undefined>(undefined);
  const [leaveOpen, setLeaveOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [calendarMonth, setCalendarMonth] = useState(dateKey().slice(0, 7));
  const [draft, setDraft] = useState({ leaveType: "annual" as LeaveRequest["leaveType"], fromDate: addDays(dateKey(), 1), toDate: addDays(dateKey(), 1), reason: "" });
  const { showToast } = useToast();
  const load = useCallback(() => { if (systemAdmin) { setOverview(null); return; } void mockApi.hr.getSelfServiceOverview().then((data) => setOverview(data ?? null)); }, [systemAdmin]);
  useEffect(() => { load(); }, [load]);
  if (systemAdmin) return <section className="sales-content employee-self-service"><div className="content-heading"><div><p className="eyebrow dark">TÀI KHOẢN CỦA TÔI</p><h2>Hồ sơ System Admin</h2><p>Đây là tài khoản quản trị hệ thống, không thuộc hồ sơ nhân viên nên không thực hiện chấm công hoặc gửi đơn nghỉ.</p></div></div><div className="employee-profile-card"><div className="employee-profile-avatar">{(user?.name ?? "A").split(" ").slice(-1)[0].slice(0, 1)}</div><div><strong>{user?.name ?? "System Admin"}</strong><span>{user?.email ?? "—"}</span></div><StatusBadge status="active" /></div><article className="detail-section"><div className="section-heading"><div><h3>Phạm vi truy cập</h3><p>Thông tin tài khoản dùng để quản trị và mô phỏng role.</p></div></div><div className="structure-list"><div><strong>Role đang sử dụng</strong><span>{activeRole()}</span></div><div><strong>Phạm vi dữ liệu</strong><span>{user?.scope ?? "Tất cả chi nhánh"}</span></div><div><strong>Không gian cá nhân</strong><span>Không áp dụng chấm công, nghỉ phép và bảng lương cho System Admin.</span></div></div></article></section>;
  if (overview === undefined) return <section className="sales-content"><div className="detail-loading">Đang tải không gian nhân viên...</div></section>;
  if (overview === null) return <section className="sales-content"><div className="detail-loading">Tài khoản này chưa được liên kết với hồ sơ nhân viên. Vui lòng liên hệ HR.</div></section>;
  const clock = async (action: "in" | "out") => { setSaving(true); const result = action === "in" ? await mockApi.hr.checkIn(overview.employee.id) : await mockApi.hr.checkOut(overview.employee.id); setSaving(false); if (result.errors.form || result.errors.employeeId) showToast(result.errors.form ?? result.errors.employeeId, "error"); else { const time = action === "in" ? result.entity?.checkIn : result.entity?.checkOut; showToast(action === "in" ? `Bạn đã check-in lúc ${time}.` : `Bạn đã check-out lúc ${time}.`, "success"); load(); } };
  const submitLeave = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await mockApi.hr.createLeaveRequest({ employeeId: overview.employee.id, ...draft }); setSaving(false); if (Object.keys(result.errors).length) { showToast(result.errors.dates ?? result.errors.reason ?? result.errors.form ?? "Không thể gửi đơn nghỉ.", "error"); return; } setLeaveOpen(false); showToast("Đã gửi đơn nghỉ, đang chờ quản lý phê duyệt.", "success"); load(); };
  const canCheckIn = !overview.attendance.checkIn && overview.attendance.status !== "on_leave";
  const canCheckOut = Boolean(overview.attendance.checkIn) && !overview.attendance.checkOut;
  return <section className="sales-content employee-self-service">
    <div className="content-heading"><div><p className="eyebrow dark">KHÔNG GIAN NHÂN VIÊN</p><h2>Chấm công & nghỉ phép</h2><p>Chào {overview.employee.fullName}. Bạn chỉ có thể xem và thao tác dữ liệu của chính mình.</p></div><button className="secondary-button" onClick={() => setLeaveOpen(true)}>＋ Gửi đơn nghỉ</button></div>
    <div className="employee-profile-card"><div className="employee-profile-avatar">{overview.employee.fullName.split(" ").slice(-1)[0].slice(0, 1)}</div><div><strong>{overview.employee.employeeNo} · {overview.employee.fullName}</strong><span>{overview.employee.department} · {overview.employee.title}</span></div><StatusBadge status={overview.employee.status} /></div>
    <div className="employee-attendance-card"><div><span>CHẤM CÔNG HÔM NAY</span><strong>{formatDate(overview.asOfDate)}</strong><small>{overview.attendance.status === "on_leave" ? "Bạn đang nghỉ phép đã được duyệt." : "Giờ vào/ra được ghi nhận tại đúng thời điểm bạn bấm nút."}</small></div><div className="employee-clock-times"><span>Vào <b>{overview.attendance.checkIn ?? "Chưa check-in"}</b></span><span>Ra <b>{overview.attendance.checkOut ?? "Chưa check-out"}</b></span></div><div className="detail-actions">{canCheckIn && <button disabled={saving} className="primary-button compact" onClick={() => void clock("in")}>Check-in</button>}{canCheckOut && <button disabled={saving} className="primary-button compact" onClick={() => void clock("out")}>Check-out</button>}{!canCheckIn && !canCheckOut && <StatusBadge status={overview.attendance.status} />}</div></div>
    <AttendanceCalendar title="Lịch chấm công của tôi" description="Theo dõi trạng thái có mặt, đi trễ và lịch nghỉ theo tháng." month={calendarMonth} onMonthChange={setCalendarMonth} events={personalCalendarEvents(overview.asOfDate, overview.attendance, overview.leaveRequests)} />
    <article className="detail-section employee-leave-card"><div className="section-heading"><div><h3>Đơn nghỉ của tôi</h3><p>Các đơn nghỉ chờ duyệt, đã duyệt và bị từ chối.</p></div></div>{overview.leaveRequests.length ? <div className="hr-leave-list">{overview.leaveRequests.map((request) => <div className="hr-leave-row" key={request.id}><div><strong>{request.requestNo} · {request.leaveType === "annual" ? "Nghỉ phép năm" : request.leaveType === "sick" ? "Nghỉ ốm" : "Nghỉ không lương"}</strong><span>{formatDate(request.fromDate)} – {formatDate(request.toDate)} · {request.totalDays} ngày<br />{request.reason}</span></div><StatusBadge status={request.status} /></div>)}</div> : <p className="muted-text">Bạn chưa có đơn nghỉ nào.</p>}</article>
    <Modal isOpen={leaveOpen} title="Gửi đơn nghỉ phép" onClose={() => setLeaveOpen(false)}><form className="crm-form" onSubmit={submitLeave}><label>Loại nghỉ<select value={draft.leaveType} onChange={(event) => setDraft({ ...draft, leaveType: event.target.value as LeaveRequest["leaveType"] })}><option value="annual">Nghỉ phép năm</option><option value="sick">Nghỉ ốm</option><option value="unpaid">Nghỉ không lương</option></select></label><div className="form-grid two-columns"><label>Từ ngày<input type="date" value={draft.fromDate} onChange={(event) => setDraft({ ...draft, fromDate: event.target.value })} /></label><label>Đến ngày<input type="date" value={draft.toDate} onChange={(event) => setDraft({ ...draft, toDate: event.target.value })} /></label></div><label>Lý do<input value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value })} placeholder="Nhập lý do nghỉ" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setLeaveOpen(false)}>Hủy</button><button disabled={saving} className="primary-button compact">{saving ? "Đang gửi..." : "Gửi phê duyệt"}</button></div></form></Modal>
  </section>;
}
