import { useCallback, useEffect, useState } from "react";
import { Column, DataTable } from "../../components/ui/DataTable";
import { Modal } from "../../components/ui/Modal";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { useToast } from "../../components/ui/Toast";
import { isSelfServiceOnly } from "../../lib/accessControl";
import { AttendanceAdjustmentDraft, AttendanceRecord, EmploymentContract, HrEmployee, HrOverview, LeaveRequest, PayrollEntry, PayrollLine, mockApi } from "../../lib/mockApi";
import { EmployeeSelfServicePage } from "./EmployeeSelfServicePage";
import { AttendanceCalendar, teamLeaveCalendarEvents } from "./AttendanceCalendar";

const formatVnd = (value: number) => `${value.toLocaleString("vi-VN")} đ`;
const formatDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("vi-VN");
const employeeName = (employees: HrEmployee[], id: string) => employees.find((employee) => employee.id === id)?.fullName ?? "Không xác định";
const dateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const addDays = (value: string, days: number) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + days); return dateKey(date); };
const nextBusinessDate = addDays(dateKey(), 1);

export function HrPage() {
  return isSelfServiceOnly() ? <EmployeeSelfServicePage /> : <HrAdminPage />;
}

function HrAdminPage() {
  const [overview, setOverview] = useState<HrOverview | null>(null);
  const [leaveOpen, setLeaveOpen] = useState(false); const [contractOpen, setContractOpen] = useState(false); const [payrollOpen, setPayrollOpen] = useState(false); const [attendanceOpen, setAttendanceOpen] = useState(false);
  const [calendarMonth, setCalendarMonth] = useState(dateKey().slice(0, 7));
  const [selectedEmployeeId, setSelectedEmployeeId] = useState(""); const [selectedPayrollId, setSelectedPayrollId] = useState(""); const [saving, setSaving] = useState(false);
  const [leaveDraft, setLeaveDraft] = useState({ employeeId: "", leaveType: "annual" as LeaveRequest["leaveType"], fromDate: nextBusinessDate, toDate: nextBusinessDate, reason: "" });
  const [contractDraft, setContractDraft] = useState({ employeeId: "", salaryStructureId: "", startDate: "2026-09-01", endDate: "2027-08-31" });
  const [payrollDraft, setPayrollDraft] = useState({ period: dateKey().slice(0, 7), paymentDate: addDays(dateKey(), 20) });
  const [attendanceDraft, setAttendanceDraft] = useState<AttendanceAdjustmentDraft>({ employeeId: "", checkIn: "", checkOut: "", reason: "" });
  const { showToast } = useToast();
  const load = useCallback(() => { void mockApi.hr.getOverview().then((data) => { setOverview(data); setSelectedPayrollId((current) => current && data.payrollEntries.some((item) => item.id === current) ? current : data.payrollEntries[0]?.id ?? ""); }); }, []);
  useEffect(() => { load(); }, [load]);
  const selectedPayroll = overview?.payrollEntries.find((item) => item.id === selectedPayrollId) ?? overview?.payrollEntries[0];
  if (!overview) return <section className="sales-content"><div className="detail-loading">Đang tải dữ liệu nhân sự...</div></section>;

  const submitAttendanceAdjustment = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await mockApi.hr.adjustAttendance(attendanceDraft); setSaving(false); if (Object.keys(result.errors).length) { showToast(result.errors.employeeId ?? result.errors.checkIn ?? result.errors.checkOut ?? result.errors.reason ?? result.errors.form ?? "Không thể điều chỉnh chấm công.", "error"); return; } setAttendanceOpen(false); showToast("Đã điều chỉnh chấm công và lưu vết người thực hiện.", "success"); load(); };
  const submitLeave = async (event: React.FormEvent) => { event.preventDefault(); const result = await mockApi.hr.createLeaveRequest(leaveDraft); if (Object.keys(result.errors).length) { showToast(result.errors.employeeId ?? result.errors.dates ?? result.errors.reason ?? "Không thể tạo đơn nghỉ.", "error"); return; } setLeaveOpen(false); showToast("Đã gửi đơn nghỉ chờ phê duyệt.", "success"); load(); };
  const decide = async (id: string, approved: boolean) => { const result = await mockApi.hr.decideLeaveRequest(id, approved); if (result.errors.form) showToast(result.errors.form, "error"); else { showToast(approved ? "Đã phê duyệt đơn nghỉ." : "Đã từ chối đơn nghỉ.", "success"); load(); } };
  const submitContract = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await mockApi.hr.createEmploymentContract(contractDraft); setSaving(false); if (Object.keys(result.errors).length) { showToast(result.errors.employeeId ?? result.errors.salaryStructureId ?? result.errors.dates ?? "Không thể lập hợp đồng.", "error"); return; } setContractOpen(false); showToast(`Đã tạo hợp đồng ${result.entity?.contractNo}.`, "success"); load(); };
  const submitPayroll = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const result = await mockApi.hr.createPayroll(payrollDraft); setSaving(false); if (Object.keys(result.errors).length) { showToast(result.errors.period ?? result.errors.paymentDate ?? result.errors.form ?? "Không thể lập bảng lương.", "error"); return; } setPayrollOpen(false); showToast(`Đã lập bảng lương ${result.entity?.payrollNo}.`, "success"); load(); };
  const updatePayroll = async (entry: PayrollEntry, action: "approve" | "pay") => { setSaving(true); const result = action === "approve" ? await mockApi.hr.approvePayroll(entry.id) : await mockApi.hr.payPayroll(entry.id, entry.paymentDate ?? `${entry.period}-28`); setSaving(false); if (result.errors.form || result.errors.paymentDate) showToast(result.errors.form ?? result.errors.paymentDate, "error"); else { showToast(action === "approve" ? "Đã duyệt bảng lương và ghi nhận chi phí phải trả." : "Đã ghi nhận chi trả lương qua ngân hàng.", "success"); load(); } };

  const employees: Column<HrEmployee>[] = [
    { key: "employee", header: "Nhân viên", render: (employee) => <div className="cell-main"><strong>{employee.employeeNo} · {employee.fullName}</strong><span>{employee.email}</span></div> },
    { key: "position", header: "Phòng ban / Chức danh", render: (employee) => <div className="cell-main"><strong>{employee.department}</strong><span>{employee.title}</span></div> },
    { key: "join", header: "Ngày vào làm", render: (employee) => formatDate(employee.joinDate) },
    { key: "status", header: "Trạng thái", render: (employee) => <StatusBadge status={employee.status} /> },
  ];
  const attendance: Column<AttendanceRecord>[] = [
    { key: "employee", header: "Nhân viên", render: (record) => <strong>{employeeName(overview.employees, record.employeeId)}</strong> },
    { key: "checkin", header: "Vào / Ra", render: (record) => <span>{record.checkIn ?? "—"} / {record.checkOut ?? "—"}</span> },
    { key: "status", header: "Trạng thái", render: (record) => <StatusBadge status={record.status} /> },
    { key: "source", header: "Ghi nhận", render: (record) => record.adjustedBy ? <span className="cell-main"><strong>Điều chỉnh</strong><span>{record.adjustedBy}<br />{record.note}</span></span> : <span className="muted-text">Tự chấm công</span> },
    { key: "action", header: "", className: "text-right", render: (record) => record.status === "on_leave" ? <span className="muted-text">Nghỉ đã duyệt</span> : <button className="reference-button" onClick={() => { setAttendanceDraft({ employeeId: record.employeeId, checkIn: record.checkIn ?? "", checkOut: record.checkOut ?? "", reason: "" }); setAttendanceOpen(true); }}>Điều chỉnh</button> },
  ];
  const contracts: Column<EmploymentContract>[] = [
    { key: "contract", header: "Hợp đồng", render: (contract) => <div className="cell-main"><strong>{contract.contractNo}</strong><span>{employeeName(overview.employees, contract.employeeId)}</span></div> },
    { key: "structure", header: "Cấu trúc lương", render: (contract) => <span>{overview.salaryStructures.find((item) => item.id === contract.salaryStructureId)?.name ?? "—"}</span> },
    { key: "term", header: "Thời hạn", render: (contract) => <span>{formatDate(contract.startDate)} – {formatDate(contract.endDate)}</span> },
    { key: "status", header: "Trạng thái", render: (contract) => <StatusBadge status={contract.status} /> },
  ];
  const payrollLines: Column<PayrollLine>[] = [
    { key: "employee", header: "Nhân viên", render: (line) => <strong>{employeeName(overview.employees, line.employeeId)}</strong> },
    { key: "base", header: "Lương cơ bản", className: "text-right", render: (line) => formatVnd(line.baseSalary) },
    { key: "allowance", header: "Phụ cấp", className: "text-right", render: (line) => formatVnd(line.allowanceAmount) },
    { key: "deduction", header: "Khấu trừ BH", className: "text-right", render: (line) => formatVnd(line.deductionAmount) },
    { key: "workdays", header: "Ngày công", className: "text-right", render: (line) => <span>{line.payableWorkdays ?? "—"}/{line.scheduledWorkdays ?? "—"}{line.unpaidLeaveDays ? ` · nghỉ KLG ${line.unpaidLeaveDays}` : ""}</span> },
    { key: "net", header: "Thực nhận", className: "text-right", render: (line) => <strong>{formatVnd(line.netAmount)}</strong> },
  ];

  return <section className="sales-content hr-page">
    <div className="content-heading"><div><p className="eyebrow dark">NHÂN SỰ</p><h2>Nhân sự, hợp đồng & bảng lương</h2><p>Từ hồ sơ và chấm công đến lập, duyệt, chi trả lương theo cấu trúc lương và hợp đồng hiệu lực.</p></div><div className="detail-actions"><button className="secondary-button" onClick={() => { setContractDraft({ employeeId: overview.employees.find((item) => item.status === "active")?.id ?? "", salaryStructureId: overview.salaryStructures.find((item) => item.status === "active")?.id ?? "", startDate: "2027-01-01", endDate: "2027-12-31" }); setContractOpen(true); }}>＋ Hợp đồng</button><button className="primary-button compact" onClick={() => setPayrollOpen(true)}>＋ Lập bảng lương</button></div></div>
    <div className="hr-summary"><article><span>Nhân viên đang làm việc</span><strong>{overview.employees.filter((item) => item.status === "active").length}</strong><small>Trong tổng số {overview.employees.length} hồ sơ nhân sự</small></article><article><span>Hợp đồng hiệu lực</span><strong>{overview.contracts.filter((item) => item.status === "active").length}</strong><small>Điều kiện bắt buộc để đưa vào bảng lương</small></article><article className="warning"><span>Đơn nghỉ chờ duyệt</span><strong>{overview.leaveRequests.filter((item) => item.status === "pending").length}</strong><small>Cần quản lý xác nhận trước ngày nghỉ</small></article></div>
    <div className="hr-grid"><article className="detail-section"><div className="section-heading"><div><h3>Chấm công hôm nay</h3><p>Nhân viên tự chấm theo thời điểm bấm nút. Điều chỉnh thủ công luôn cần lý do và lưu người thực hiện.</p></div></div><DataTable columns={attendance} rows={overview.attendance} emptyTitle="Chưa có dữ liệu chấm công" /></article><article className="detail-section"><div className="section-heading"><div><h3>Đơn nghỉ phép</h3><p>Đơn được duyệt sẽ phản ánh trạng thái nghỉ trong kỳ.</p></div><button className="secondary-button compact" onClick={() => { setLeaveDraft({ employeeId: selectedEmployeeId, leaveType: "annual", fromDate: addDays(overview.asOfDate, 1), toDate: addDays(overview.asOfDate, 1), reason: "" }); setLeaveOpen(true); }}>＋ Tạo đơn</button></div><div className="hr-leave-list">{overview.leaveRequests.map((request) => <div className="hr-leave-row" key={request.id}><div><strong>{request.requestNo} · {employeeName(overview.employees, request.employeeId)}</strong><span>{formatDate(request.fromDate)} – {formatDate(request.toDate)} · {request.totalDays} ngày<br />{request.reason}</span></div><div className="hr-leave-actions"><StatusBadge status={request.status} />{request.status === "pending" && <><button className="reference-button" onClick={() => void decide(request.id, true)}>Duyệt</button><button className="text-danger-button" onClick={() => void decide(request.id, false)}>Từ chối</button></>}</div></div>)}</div></article></div>
    <AttendanceCalendar title="Lịch nghỉ nhân sự" description="Xem nhanh tình trạng nghỉ của đội để chủ động phân bổ nhân sự theo ngày." month={calendarMonth} onMonthChange={setCalendarMonth} events={teamLeaveCalendarEvents(overview.leaveRequests, (employeeId) => employeeName(overview.employees, employeeId))} emptyText="Không có đơn nghỉ đang chờ duyệt hoặc đã duyệt trong tháng này." />
    <div className="content-subheading"><div><h3>Bảng lương</h3><p>Lương được quy đổi theo ngày công của hợp đồng và trừ ngày nghỉ không lương đã duyệt. Người lập, duyệt và chi không thể tự làm cùng bước.</p></div>{overview.payrollEntries.length > 1 && <select className="compact-select" value={selectedPayroll?.id ?? ""} onChange={(event) => setSelectedPayrollId(event.target.value)}>{overview.payrollEntries.map((item) => <option key={item.id} value={item.id}>{item.payrollNo} · {item.status}</option>)}</select>}</div>
    {selectedPayroll ? <article className="detail-section payroll-panel"><div className="payroll-panel-heading"><div><strong>{selectedPayroll.payrollNo}</strong><span>Kỳ {selectedPayroll.period} · Dự kiến chi {selectedPayroll.paymentDate ? formatDate(selectedPayroll.paymentDate) : "—"}<br />Lập: {selectedPayroll.createdBy ?? "Dữ liệu khởi tạo"} · Duyệt: {selectedPayroll.approvedBy ?? "Chưa duyệt"} · Chi: {selectedPayroll.paidBy ?? "Chưa chi"}</span></div><div className="detail-actions"><StatusBadge status={selectedPayroll.status} />{selectedPayroll.status === "draft" && <button disabled={saving} className="primary-button compact" onClick={() => void updatePayroll(selectedPayroll, "approve")}>Duyệt bảng lương</button>}{selectedPayroll.status === "approved" && <button disabled={saving} className="primary-button compact" onClick={() => void updatePayroll(selectedPayroll, "pay")}>Ghi nhận chi lương</button>}</div></div><div className="payroll-totals"><span>Tổng thu nhập <strong>{formatVnd(selectedPayroll.totalGross)}</strong></span><span>Khấu trừ <strong>{formatVnd(selectedPayroll.totalDeduction)}</strong></span><span>Thực chi <strong>{formatVnd(selectedPayroll.totalNet)}</strong></span></div><DataTable columns={payrollLines} rows={selectedPayroll.lines} emptyTitle="Chưa có dòng lương" /></article> : <article className="detail-section"><p className="muted-text">Chưa có bảng lương. Hãy lập bảng lương cho một kỳ có nhân viên hợp đồng hiệu lực.</p></article>}
    <div className="hr-contract-grid"><article className="detail-section"><div className="section-heading"><div><h3>Cấu trúc lương</h3><p>Mức lương, phụ cấp và tỷ lệ bảo hiểm dùng để lập bảng lương.</p></div></div><div className="structure-list">{overview.salaryStructures.map((structure) => <div key={structure.id}><strong>{structure.code} · {structure.name}</strong><span>Lương cơ bản {formatVnd(structure.baseSalary)} · Phụ cấp {formatVnd(structure.allowanceAmount)} · BH {Math.round(structure.insuranceRate * 1000) / 10}%</span></div>)}</div></article><article className="detail-section"><div className="section-heading"><div><h3>Hợp đồng lao động</h3><p>Nhân viên không có hợp đồng hiệu lực sẽ không được đưa vào bảng lương.</p></div></div><DataTable columns={contracts} rows={overview.contracts} emptyTitle="Chưa có hợp đồng" /></article></div>
    <div className="content-subheading"><div><h3>Hồ sơ nhân viên</h3><p>Danh mục nguồn cho chấm công, hợp đồng và bảng lương.</p></div></div><div className="list-panel"><DataTable columns={employees} rows={overview.employees} emptyTitle="Chưa có nhân viên" /></div>
    <Modal isOpen={leaveOpen} title="Tạo đơn nghỉ phép" onClose={() => setLeaveOpen(false)}><form className="crm-form" onSubmit={submitLeave}><label>Nhân viên<select value={leaveDraft.employeeId} onChange={(event) => { setSelectedEmployeeId(event.target.value); setLeaveDraft({ ...leaveDraft, employeeId: event.target.value }); }}><option value="">Chọn nhân viên</option>{overview.employees.filter((employee) => employee.status === "active").map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNo} · {employee.fullName}</option>)}</select></label><label>Loại nghỉ<select value={leaveDraft.leaveType} onChange={(event) => setLeaveDraft({ ...leaveDraft, leaveType: event.target.value as LeaveRequest["leaveType"] })}><option value="annual">Nghỉ phép năm</option><option value="sick">Nghỉ ốm</option><option value="unpaid">Nghỉ không lương</option></select></label><div className="form-grid two-columns"><label>Từ ngày<input type="date" value={leaveDraft.fromDate} onChange={(event) => setLeaveDraft({ ...leaveDraft, fromDate: event.target.value })} /></label><label>Đến ngày<input type="date" value={leaveDraft.toDate} onChange={(event) => setLeaveDraft({ ...leaveDraft, toDate: event.target.value })} /></label></div><label>Lý do<input value={leaveDraft.reason} onChange={(event) => setLeaveDraft({ ...leaveDraft, reason: event.target.value })} placeholder="Nhập lý do nghỉ" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setLeaveOpen(false)}>Hủy</button><button className="primary-button compact">Gửi phê duyệt</button></div></form></Modal>
    <Modal isOpen={attendanceOpen} title="Điều chỉnh chấm công" onClose={() => setAttendanceOpen(false)}><form className="crm-form" onSubmit={submitAttendanceAdjustment}><p className="form-hint">Chỉ dùng khi cần sửa dữ liệu thực tế. Hệ thống lưu lý do, người thực hiện và thời điểm điều chỉnh.</p><label>Nhân viên<select value={attendanceDraft.employeeId} onChange={(event) => setAttendanceDraft({ ...attendanceDraft, employeeId: event.target.value })}><option value="">Chọn nhân viên</option>{overview.employees.filter((employee) => employee.status === "active").map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNo} · {employee.fullName}</option>)}</select></label><div className="form-grid two-columns"><label>Giờ vào<input type="time" value={attendanceDraft.checkIn ?? ""} onChange={(event) => setAttendanceDraft({ ...attendanceDraft, checkIn: event.target.value })} /></label><label>Giờ ra<input type="time" value={attendanceDraft.checkOut ?? ""} onChange={(event) => setAttendanceDraft({ ...attendanceDraft, checkOut: event.target.value })} /></label></div><label>Lý do điều chỉnh<input value={attendanceDraft.reason} onChange={(event) => setAttendanceDraft({ ...attendanceDraft, reason: event.target.value })} placeholder="Ví dụ: thiết bị chấm công lỗi" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setAttendanceOpen(false)}>Hủy</button><button disabled={saving} className="primary-button compact">{saving ? "Đang lưu..." : "Xác nhận điều chỉnh"}</button></div></form></Modal>
    <Modal isOpen={contractOpen} title="Lập hợp đồng lao động" onClose={() => setContractOpen(false)}><form className="crm-form" onSubmit={submitContract}><label>Nhân viên<select value={contractDraft.employeeId} onChange={(event) => setContractDraft({ ...contractDraft, employeeId: event.target.value })}>{overview.employees.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.employeeNo} · {item.fullName}</option>)}</select></label><label>Cấu trúc lương<select value={contractDraft.salaryStructureId} onChange={(event) => setContractDraft({ ...contractDraft, salaryStructureId: event.target.value })}>{overview.salaryStructures.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><div className="form-grid two-columns"><label>Từ ngày<input type="date" value={contractDraft.startDate} onChange={(event) => setContractDraft({ ...contractDraft, startDate: event.target.value })} /></label><label>Đến ngày<input type="date" value={contractDraft.endDate} onChange={(event) => setContractDraft({ ...contractDraft, endDate: event.target.value })} /></label></div><p className="form-hint">Hệ thống chặn hợp đồng hiệu lực bị trùng thời gian cho cùng một nhân viên.</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setContractOpen(false)}>Hủy</button><button disabled={saving} className="primary-button compact">{saving ? "Đang lưu..." : "Tạo hợp đồng"}</button></div></form></Modal>
    <Modal isOpen={payrollOpen} title="Lập bảng lương" onClose={() => setPayrollOpen(false)}><form className="crm-form" onSubmit={submitPayroll}><label>Kỳ lương<input type="month" value={payrollDraft.period} onChange={(event) => setPayrollDraft({ ...payrollDraft, period: event.target.value })} /></label><label>Ngày dự kiến chi<input type="date" value={payrollDraft.paymentDate} onChange={(event) => setPayrollDraft({ ...payrollDraft, paymentDate: event.target.value })} /></label><p className="form-hint">Bảng lương lấy nhân viên đang làm việc có hợp đồng và cấu trúc lương hiệu lực trong kỳ. Không thể lập trùng kỳ.</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setPayrollOpen(false)}>Hủy</button><button disabled={saving} className="primary-button compact">{saving ? "Đang lập..." : "Lập bảng lương"}</button></div></form></Modal>
  </section>;
}
