import { FormEvent, useState } from "react";
import { DEMO_ACCOUNTS } from "../lib/demoAccounts";

const DEMO_EMAIL = DEMO_ACCOUNTS[0].email;
const DEMO_PASSWORD = DEMO_ACCOUNTS[0].password;
function Brand({ light = false }: { light?: boolean }) { return <div className={`brand ${light ? "brand-light" : ""}`} aria-label="MBWNext"><span className="brand-mark">MBW</span><span className="brand-divider" /><span className="brand-name">Next</span></div>; }

export function LoginPage({ onSuccess }: { onSuccess: (email: string) => string | undefined }) {
  const [email, setEmail] = useState(DEMO_EMAIL); const [password, setPassword] = useState(DEMO_PASSWORD); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const account = DEMO_ACCOUNTS.find((item) => item.email === email.trim().toLowerCase() && item.password === password); if (account) { const signInError = onSuccess(account.email); if (signInError) setError(signInError); return; } setError("Email hoặc mật khẩu chưa đúng. Hãy dùng thông tin tài khoản mẫu bên dưới."); };
  return <main className="login-page"><section className="login-intro"><div className="login-intro-content"><Brand light /><p className="eyebrow">NỀN TẢNG VẬN HÀNH DOANH NGHIỆP</p><h1>Một nơi để điều hành toàn bộ hoạt động kinh doanh.</h1><p className="intro-copy">Kết nối bán hàng, mua hàng, kho, tài chính và đội ngũ trong một hệ thống nhất quán.</p><div className="feature-list"><div><span>✓</span> Dữ liệu vận hành theo thời gian thực</div><div><span>✓</span> Phê duyệt chứng từ minh bạch</div><div><span>✓</span> Báo cáo ra quyết định tức thì</div></div></div><div className="login-abstract login-circle-one" /><div className="login-abstract login-circle-two" /><div className="login-grid" /></section><section className="login-panel"><form className="login-form" onSubmit={submit}><div className="mobile-brand"><Brand /></div><div className="login-heading"><p className="eyebrow dark">CHÀO MỪNG TRỞ LẠI</p><h2>Đăng nhập MBWNext</h2><p>Nhập thông tin để tiếp tục làm việc.</p></div><label>Email công việc<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="name@company.vn" /></label><label>Mật khẩu<div className="password-field"><input value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? "text" : "password"} autoComplete="current-password" placeholder="Nhập mật khẩu" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Ẩn mật khẩu" : "Hiện mật khẩu"}>{showPassword ? "Ẩn" : "Hiện"}</button></div></label><div className="login-options"><label className="remember"><input type="checkbox" defaultChecked /> <span>Ghi nhớ đăng nhập</span></label><button className="text-button" type="button">Quên mật khẩu?</button></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" type="submit">Đăng nhập <span>→</span></button><div className="demo-credentials"><span className="demo-dot" /><div><strong>Tài khoản mẫu</strong><br />{DEMO_EMAIL} · {DEMO_PASSWORD}</div></div></form></section></main>;
}
