import { useCallback, useEffect, useState } from "react";
import { Column, DataTable } from "../../components/ui/DataTable";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { useToast } from "../../components/ui/Toast";
import { formatVnd } from "../../data/mockData";
import { Project, ProjectOverview, ProjectTask, mockApi } from "../../lib/mockApi";

export function ProjectsPage() {
  const [overview, setOverview] = useState<ProjectOverview | null>(null); const { showToast } = useToast(); const load = useCallback(() => { void mockApi.projects.getOverview().then(setOverview); }, []); useEffect(() => { load(); }, [load]);
  if (!overview) return <section className="sales-content"><div className="detail-loading">Đang tải dữ liệu dự án...</div></section>;
  const updateTask = async (task: ProjectTask, progressPercent: number) => { const status = progressPercent === 100 ? "completed" : progressPercent > 0 ? "in_progress" : "not_started" as const; const result = await mockApi.projects.updateTask(task.id, { status, progressPercent }); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.progressPercent ?? "Không thể cập nhật nhiệm vụ.", "error"); else { showToast("Đã cập nhật tiến độ nhiệm vụ.", "success"); load(); } };
  const projects: Column<Project>[] = [{ key: "project", header: "Dự án", render: (project) => <div className="cell-main"><strong>{project.code} · {project.name}</strong><span>Quản lý: {project.managerName}</span></div> }, { key: "timeline", header: "Thời gian", render: (project) => <span>{new Date(`${project.startDate}T00:00:00`).toLocaleDateString("vi-VN")} – {new Date(`${project.endDate}T00:00:00`).toLocaleDateString("vi-VN")}</span> }, { key: "financial", header: "Ngân sách / Chi phí", render: (project) => <div className="cell-main"><strong>{formatVnd(project.budgetAmount)}</strong><span>Đã chi {formatVnd(project.actualCost)} · Thu {formatVnd(project.actualRevenue)}</span></div> }, { key: "progress", header: "Tiến độ", render: (project) => <div className="project-progress"><span><i style={{ width: `${project.progressPercent}%` }} /></span><strong>{project.progressPercent}%</strong></div> }, { key: "status", header: "Trạng thái", render: (project) => <StatusBadge status={project.status} /> }];
  const tasks: Column<ProjectTask>[] = [{ key: "task", header: "Nhiệm vụ", render: (task) => <div className="cell-main"><strong>{task.code} · {task.title}</strong><span>Phụ trách: {task.assigneeName} · Hạn {new Date(`${task.dueDate}T00:00:00`).toLocaleDateString("vi-VN")}</span></div> }, { key: "status", header: "Trạng thái", render: (task) => <StatusBadge status={task.status} /> }, { key: "progress", header: "Tiến độ", render: (task) => <div className="task-progress"><input type="number" min="0" max="100" defaultValue={task.progressPercent} onBlur={(event) => { const next = Number(event.target.value); if (next !== task.progressPercent) void updateTask(task, next); }} /><span>%</span></div> }];
  return <section className="sales-content projects-page"><div className="content-heading"><div><p className="eyebrow dark">DỰ ÁN & CÔNG VIỆC</p><h2>Điều hành dự án</h2><p>Theo dõi tiến độ, ngân sách, chi phí và nhiệm vụ theo từng dự án.</p></div></div><div className="project-summary"><article><span>Dự án đang triển khai</span><strong>{overview.projects.filter((project) => project.status === "in_progress").length}</strong></article><article><span>Nhiệm vụ đang làm</span><strong>{overview.tasks.filter((task) => task.status === "in_progress").length}</strong></article><article><span>Nhiệm vụ hoàn thành</span><strong>{overview.tasks.filter((task) => task.status === "completed").length}</strong></article></div><div className="list-panel"><DataTable columns={projects} rows={overview.projects} emptyTitle="Chưa có dự án" /></div><div className="content-subheading"><div><h3>Nhiệm vụ & timeline</h3><p>Cập nhật tiến độ sẽ tự chuyển trạng thái nhiệm vụ.</p></div></div><div className="project-timeline">{overview.tasks.map((task) => <article key={task.id}><strong>{task.title}</strong><span>{task.startDate} → {task.dueDate}</span><div><i style={{ width: `${task.progressPercent}%` }} /></div><small>{task.progressPercent}% · {task.assigneeName}</small></article>)}</div><div className="list-panel"><DataTable columns={tasks} rows={overview.tasks} emptyTitle="Chưa có nhiệm vụ" /></div></section>;
}
