import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Column, DataTable } from "../../components/ui/DataTable";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { useToast } from "../../components/ui/Toast";
import { formatVnd } from "../../data/mockData";
import { Project, ProjectDraft, ProjectFinancialEntry, ProjectOverview, ProjectTask, ProjectTaskDraft, ProjectTimesheet, mockApi } from "../../lib/mockApi";

const formatDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("vi-VN");
const daysBetween = (from: string, to: string) => Math.round((new Date(`${to}T00:00:00`).getTime() - new Date(`${from}T00:00:00`).getTime()) / 86_400_000);

export function ProjectsPage() {
  const [overview, setOverview] = useState<ProjectOverview | null>(null);
  const [selectedProjectId, setSelectedProjectId] = useState("");
  const [modal, setModal] = useState<"timesheet" | "financial" | "project" | "task" | "comment" | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [timesheet, setTimesheet] = useState({ taskId: "", employeeId: "", workDate: "2026-08-29", hours: "", note: "" });
  const [financial, setFinancial] = useState({ entryType: "expense" as "expense" | "revenue", sourceDocumentNo: "" });
  const [projectForm, setProjectForm] = useState<ProjectDraft>({ name: "", customerId: "", managerId: "", teamMemberIds: [], startDate: "2026-09-01", endDate: "2026-10-31", budgetAmount: 0, status: "not_started" });
  const [taskForm, setTaskForm] = useState<ProjectTaskDraft>({ projectId: "", title: "", assigneeId: "", startDate: "", dueDate: "", priority: "medium", isMilestone: false, predecessorIds: [] });
  const [comment, setComment] = useState({ taskId: "", message: "", attachmentName: "" });
  const { showToast } = useToast();
  const load = useCallback(() => { void mockApi.projects.getOverview().then((data) => { setOverview(data); setSelectedProjectId((current) => current || data.projects[0]?.id || ""); }); }, []);
  useEffect(() => { load(); }, [load]);
  const selectedProject = overview?.projects.find((project) => project.id === selectedProjectId) ?? overview?.projects[0];
  const projectTasks = useMemo(() => overview?.tasks.filter((task) => task.projectId === selectedProject?.id) ?? [], [overview, selectedProject?.id]);
  const projectTimesheets = useMemo(() => overview?.timesheets.filter((entry) => entry.projectId === selectedProject?.id) ?? [], [overview, selectedProject?.id]);
  const projectEntries = useMemo(() => overview?.financialEntries.filter((entry) => entry.projectId === selectedProject?.id) ?? [], [overview, selectedProject?.id]);
  const approvedHours = projectTimesheets.filter((entry) => entry.status === "approved").reduce((total, entry) => total + entry.hours, 0);
  const availableFinancialSources = useMemo(() => overview?.financialSources.filter((source) => source.entryType === financial.entryType && !overview.financialEntries.some((entry) => entry.sourceDocumentNo === source.documentNo)) ?? [], [financial.entryType, overview]);

  const updateTask = async (task: ProjectTask, progressPercent: number) => {
    const status = progressPercent === 100 ? "completed" : progressPercent > 0 ? "in_progress" : "not_started" as const;
    const result = await mockApi.projects.updateTask(task.id, { status, progressPercent });
    if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.progressPercent ?? "Không thể cập nhật nhiệm vụ.", "error");
    else { showToast("Đã cập nhật tiến độ nhiệm vụ.", "success"); load(); }
  };
  const openTimesheet = () => { setErrors({}); setTimesheet({ taskId: projectTasks[0]?.id ?? "", employeeId: projectTasks[0]?.assigneeId ?? "", workDate: projectTasks[0]?.startDate ?? "2026-08-29", hours: "", note: "" }); setModal("timesheet"); };
  const openFinancial = () => { setErrors({}); const source = overview?.financialSources.find((entry) => entry.entryType === "expense" && !overview.financialEntries.some((item) => item.sourceDocumentNo === entry.documentNo)); setFinancial({ entryType: "expense", sourceDocumentNo: source?.documentNo ?? "" }); setModal("financial"); };
  const submitTimesheet = async (event: FormEvent) => { event.preventDefault(); if (!selectedProject) return; const result = await mockApi.projects.createTimesheet({ projectId: selectedProject.id, taskId: timesheet.taskId, employeeId: timesheet.employeeId, workDate: timesheet.workDate, hours: Number(timesheet.hours), note: timesheet.note }); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } showToast("Đã gửi bảng công, chờ quản lý duyệt.", "success"); setModal(null); load(); };
  const submitFinancial = async (event: FormEvent) => { event.preventDefault(); if (!selectedProject) return; const result = await mockApi.projects.createFinancialEntry({ projectId: selectedProject.id, sourceDocumentNo: financial.sourceDocumentNo }); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } showToast(financial.entryType === "expense" ? "Đã liên kết chi phí từ hóa đơn mua." : "Đã liên kết doanh thu từ hóa đơn bán.", "success"); setModal(null); load(); };
  const reviewTimesheet = async (entry: ProjectTimesheet, status: "approved" | "rejected") => { const reason = status === "rejected" ? window.prompt("Nhập lý do từ chối bảng công:") : ""; if (status === "rejected" && !reason?.trim()) return; const result = await mockApi.projects.reviewTimesheet(entry.id, status, reason ?? ""); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.decisionReason ?? "Không thể xử lý bảng công.", "error"); else { showToast(status === "approved" ? "Đã duyệt bảng công." : "Đã từ chối bảng công.", "success"); load(); } };
  const editTimesheet = async (entry: ProjectTimesheet) => { const hours = window.prompt("Số giờ công mới:", String(entry.hours)); if (hours === null) return; const note = window.prompt("Nội dung công việc:", entry.note); if (note === null) return; const result = await mockApi.projects.updateTimesheet(entry.id, { workDate: entry.workDate, hours: Number(hours), note }); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.hours ?? "Không thể sửa bảng công.", "error"); else { showToast("Đã cập nhật bảng công.", "success"); load(); } };
  const withdrawTimesheet = async (entry: ProjectTimesheet) => { if (!window.confirm("Thu hồi bảng công này?")) return; const result = await mockApi.projects.withdrawTimesheet(entry.id); if (Object.keys(result.errors).length) showToast(result.errors.form ?? "Không thể thu hồi bảng công.", "error"); else { showToast("Đã thu hồi bảng công.", "success"); load(); } };
  const openProject = (project?: Project) => { setErrors({}); setProjectForm(project ? { id: project.id, name: project.name, customerId: project.customerId ?? "", managerId: project.managerId, teamMemberIds: project.teamMemberIds, startDate: project.startDate, endDate: project.endDate, budgetAmount: project.budgetAmount, status: project.status } : { name: "", customerId: overview?.customers[0]?.id ?? "", managerId: overview?.employees[0]?.id ?? "", teamMemberIds: [], startDate: "2026-09-01", endDate: "2026-10-31", budgetAmount: 0, status: "not_started" }); setModal("project"); };
  const openTask = (task?: ProjectTask) => { if (!selectedProject) return; setErrors({}); setTaskForm(task ? { id: task.id, projectId: task.projectId, title: task.title, assigneeId: task.assigneeId, startDate: task.startDate, dueDate: task.dueDate, priority: task.priority, isMilestone: task.isMilestone, predecessorIds: task.predecessorIds } : { projectId: selectedProject.id, title: "", assigneeId: selectedProject.teamMemberIds[0] ?? selectedProject.managerId, startDate: selectedProject.startDate, dueDate: selectedProject.endDate, priority: "medium", isMilestone: false, predecessorIds: [] }); setModal("task"); };
  const submitProject = async (event: FormEvent) => { event.preventDefault(); const result = await mockApi.projects.saveProject(projectForm); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } if (result.entity) setSelectedProjectId(result.entity.id); showToast(projectForm.id ? "Đã cập nhật dự án." : "Đã tạo dự án.", "success"); setModal(null); load(); };
  const submitTask = async (event: FormEvent) => { event.preventDefault(); const result = await mockApi.projects.saveTask(taskForm); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } showToast(taskForm.id ? "Đã cập nhật nhiệm vụ." : "Đã tạo nhiệm vụ.", "success"); setModal(null); load(); };
  const changeProjectStatus = async (status: Project["status"]) => { if (!selectedProject) return; const result = await mockApi.projects.setProjectStatus(selectedProject.id, status); if (Object.keys(result.errors).length) showToast(result.errors.form ?? "Không thể đổi trạng thái dự án.", "error"); else { showToast("Đã cập nhật vòng đời dự án.", "success"); load(); } };
  const submitComment = async (event: FormEvent) => { event.preventDefault(); const result = await mockApi.projects.addTaskComment(comment.taskId, comment.message, comment.attachmentName); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } showToast("Đã cập nhật trao đổi nhiệm vụ.", "success"); setModal(null); load(); };

  if (!overview || !selectedProject) return <section className="sales-content"><div className="detail-loading">Đang tải dữ liệu dự án...</div></section>;
  const projects: Column<Project>[] = [
    { key: "project", header: "Dự án", render: (project) => <button className={`project-select-cell ${project.id === selectedProject.id ? "is-selected" : ""}`} onClick={() => setSelectedProjectId(project.id)}><strong>{project.code} · {project.name}</strong><span>Quản lý: {project.managerName} · {project.teamMemberNames.length} thành viên</span></button> },
    { key: "timeline", header: "Thời gian", render: (project) => <span>{formatDate(project.startDate)} – {formatDate(project.endDate)}</span> },
    { key: "financial", header: "Ngân sách / thực tế", render: (project) => <div className="cell-main"><strong>{formatVnd(project.budgetAmount)}</strong><span>Chi {formatVnd(project.actualCost)} · Thu {formatVnd(project.actualRevenue)}</span></div> },
    { key: "progress", header: "Tiến độ", render: (project) => <div className="project-progress"><span><i style={{ width: `${project.progressPercent}%` }} /></span><strong>{project.progressPercent}%</strong></div> },
    { key: "status", header: "Trạng thái", render: (project) => <StatusBadge status={project.status} /> },
  ];
  const tasks: Column<ProjectTask>[] = [
    { key: "task", header: "Nhiệm vụ", render: (task) => <div className="cell-main"><strong>{task.isMilestone ? "◆ " : ""}{task.code} · {task.title}</strong><span>Phụ trách: {task.assigneeName} · Hạn {formatDate(task.dueDate)}{task.predecessorNames.length ? ` · Phụ thuộc: ${task.predecessorNames.join(", ")}` : ""}</span>{(task.comments.length || task.attachments.length) > 0 && <small>💬 {task.comments.length} · 📎 {task.attachments.length}</small>}</div> },
    { key: "priority", header: "Ưu tiên", render: (task) => <StatusBadge status={task.priority} /> },
    { key: "status", header: "Trạng thái", render: (task) => <StatusBadge status={task.status} /> },
    { key: "progress", header: "Tiến độ", render: (task) => <div className="task-progress"><input aria-label={`Tiến độ ${task.title}`} type="number" min="0" max="100" defaultValue={task.progressPercent} onBlur={(event) => { const next = Number(event.target.value); if (next !== task.progressPercent) void updateTask(task, next); }} /><span>%</span><button className="text-link" onClick={() => openTask(task)}>Sửa</button><button className="text-link" onClick={() => { setErrors({}); setComment({ taskId: task.id, message: "", attachmentName: "" }); setModal("comment"); }}>Trao đổi</button></div> },
  ];
  const timesheets: Column<ProjectTimesheet>[] = [
    { key: "work", header: "Ngày công", render: (entry) => <div className="cell-main"><strong>{entry.taskTitle}</strong><span>{formatDate(entry.workDate)} · {entry.employeeName}</span></div> },
    { key: "hours", header: "Số giờ", render: (entry) => <strong>{entry.hours} giờ</strong> },
    { key: "note", header: "Nội dung", render: (entry) => <span>{entry.note}</span> },
    { key: "status", header: "Trạng thái", render: (entry) => <div className="table-actions"><StatusBadge status={entry.status} />{entry.decisionReason && <small className="decision-note">Lý do: {entry.decisionReason}</small>}{entry.status === "submitted" && <><button className="text-link" onClick={() => void editTimesheet(entry)}>Sửa</button><button className="text-link danger" onClick={() => void withdrawTimesheet(entry)}>Thu hồi</button><button className="text-link success" onClick={() => void reviewTimesheet(entry, "approved")}>Duyệt</button><button className="text-link danger" onClick={() => void reviewTimesheet(entry, "rejected")}>Từ chối</button></>}</div> },
  ];
  const financialEntries: Column<ProjectFinancialEntry>[] = [
    { key: "document", header: "Chứng từ", render: (entry) => <div className="cell-main"><strong>{entry.sourceDocumentNo}</strong><span>{formatDate(entry.postingDate)} · {entry.description}</span></div> },
    { key: "type", header: "Loại", render: (entry) => <StatusBadge status={entry.entryType === "expense" ? "Chi phí" : "Doanh thu"} /> },
    { key: "amount", header: "Giá trị", className: "align-right", render: (entry) => <strong className={entry.entryType === "expense" ? "amount-expense" : "amount-revenue"}>{entry.entryType === "expense" ? "−" : "+"}{formatVnd(entry.amount)}</strong> },
  ];
  const ganttStart = projectTasks.length ? projectTasks.reduce((min, task) => task.startDate < min ? task.startDate : min, projectTasks[0].startDate) : selectedProject.startDate;
  const ganttEnd = projectTasks.length ? projectTasks.reduce((max, task) => task.dueDate > max ? task.dueDate : max, projectTasks[0].dueDate) : selectedProject.endDate;
  const ganttDays = Math.max(1, daysBetween(ganttStart, ganttEnd) + 1);

  return <section className="sales-content projects-page">
    <div className="content-heading"><div><p className="eyebrow dark">DỰ ÁN & CÔNG VIỆC</p><h2>Điều hành dự án</h2><p>Quản lý tiến độ, công việc, giờ công và ngân sách theo từng dự án.</p></div><button className="primary-button" onClick={() => openProject()}>+ Tạo dự án</button></div>
    <div className="project-summary"><article><span>Dự án đang triển khai</span><strong>{overview.projects.filter((project) => project.status === "in_progress").length}</strong></article><article><span>Nhiệm vụ đang làm</span><strong>{overview.tasks.filter((task) => task.status === "in_progress").length}</strong></article><article><span>Giờ công đã duyệt</span><strong>{approvedHours} giờ</strong></article></div>
    <div className="list-panel"><DataTable columns={projects} rows={overview.projects} emptyTitle="Chưa có dự án" /></div>
    <div className="project-detail-heading"><div><p className="eyebrow dark">{selectedProject.code}</p><h3>{selectedProject.name} <StatusBadge status={selectedProject.status} /></h3><p>{formatDate(selectedProject.startDate)} – {formatDate(selectedProject.endDate)} · Quản lý: {selectedProject.managerName} · Khách hàng: {selectedProject.customerName ?? "Chưa gắn"}</p></div><div className="project-detail-actions"><button className="secondary-button" onClick={() => openProject(selectedProject)}>Sửa dự án</button><button className="secondary-button" onClick={() => void changeProjectStatus(selectedProject.status === "on_hold" ? "in_progress" : "on_hold")}>{selectedProject.status === "on_hold" ? "Tiếp tục" : "Tạm dừng"}</button><button className="secondary-button" onClick={openTimesheet}>+ Ghi giờ công</button><button className="primary-button" onClick={openFinancial}>+ Ghi nhận tài chính</button>{selectedProject.status !== "completed" && <button className="primary-button" onClick={() => void changeProjectStatus("completed")}>Đóng dự án</button>}</div></div>
    <div className="project-finance-cards"><article><span>Ngân sách</span><strong>{formatVnd(selectedProject.budgetAmount)}</strong><small>Đã dùng {selectedProject.budgetUtilization}%</small></article><article><span>Chi phí thực tế</span><strong>{formatVnd(selectedProject.actualCost)}</strong><small className={selectedProject.budgetRemaining < 0 ? "warning-text" : ""}>Gồm nhân công {formatVnd(selectedProject.laborCost)} · Còn lại {formatVnd(selectedProject.budgetRemaining)}</small></article><article><span>Doanh thu ghi nhận</span><strong>{formatVnd(selectedProject.actualRevenue)}</strong><small>Lãi gộp: {formatVnd(selectedProject.actualRevenue - selectedProject.actualCost)}</small></article></div>
    <div className="content-subheading"><div><h3>Gantt & phụ thuộc công việc</h3><p>Không thể khởi động hoặc cập nhật tiến độ công việc khi nhiệm vụ phụ thuộc chưa hoàn thành.</p></div></div>
    <div className="gantt-panel"><div className="gantt-header"><span>Nhiệm vụ</span><span>{formatDate(ganttStart)} <i /> {formatDate(ganttEnd)}</span></div>{projectTasks.map((task) => { const left = Math.max(0, daysBetween(ganttStart, task.startDate) / ganttDays * 100); const width = Math.max(5, (daysBetween(task.startDate, task.dueDate) + 1) / ganttDays * 100); return <div className="gantt-row" key={task.id}><div><strong>{task.title}</strong><small>{task.predecessorNames.length ? `Sau: ${task.predecessorNames.join(", ")}` : "Không có phụ thuộc"}</small></div><div className="gantt-track"><i className={task.status} style={{ left: `${left}%`, width: `${width}%` }}><b style={{ width: `${task.progressPercent}%` }} /></i></div></div>; })}</div>
    <div className="content-subheading"><div><h3>Nhiệm vụ</h3><p>Cập nhật tiến độ sẽ tự chuyển trạng thái; nhiệm vụ có phụ thuộc được kiểm soát theo thứ tự.</p></div><button className="secondary-button" onClick={() => openTask()}>+ Tạo nhiệm vụ</button></div><div className="list-panel"><DataTable columns={tasks} rows={projectTasks} emptyTitle="Chưa có nhiệm vụ" /></div>
    <div className="project-bottom-grid"><div><div className="content-subheading"><div><h3>Timesheet</h3><p>Giờ công chỉ được tính vào báo cáo sau khi đã duyệt.</p></div></div><div className="list-panel"><DataTable columns={timesheets} rows={projectTimesheets} emptyTitle="Chưa có giờ công" /></div></div><div><div className="content-subheading"><div><h3>Chi phí & doanh thu</h3><p>Ghi nhận chứng từ phát sinh để theo dõi ngân sách dự án.</p></div></div><div className="list-panel"><DataTable columns={financialEntries} rows={projectEntries} emptyTitle="Chưa có chứng từ tài chính" /></div></div></div>
    <div className="content-subheading"><div><h3>Nhật ký dự án</h3><p>Các thay đổi quan trọng được ghi nhận trong phiên làm việc.</p></div></div><div className="project-activity-list">{overview.activities.filter((activity) => activity.projectId === selectedProject.id).length ? overview.activities.filter((activity) => activity.projectId === selectedProject.id).map((activity) => <article key={activity.id}><strong>{activity.action}</strong><span>{activity.detail}</span><small>{activity.actor} · {new Date(activity.at).toLocaleString("vi-VN")}</small></article>) : <p className="muted-text">Chưa có thay đổi mới trong phiên này.</p>}</div>
    {modal === "timesheet" && <div className="modal-backdrop"><form className="modal modal-wide project-form" onSubmit={submitTimesheet}><div className="modal-heading"><h2>Ghi giờ công dự án</h2><button type="button" onClick={() => setModal(null)}>×</button></div><p className="modal-description">Chỉ thành viên được giao nhiệm vụ mới có thể ghi giờ công. Bảng công được gửi ở trạng thái chờ duyệt.</p><div className="form-grid two-columns"><label>Nhiệm vụ<select value={timesheet.taskId} onChange={(event) => { const task = projectTasks.find((item) => item.id === event.target.value); setTimesheet({ ...timesheet, taskId: event.target.value, employeeId: task?.assigneeId ?? "", workDate: task?.startDate ?? timesheet.workDate }); }}><option value="">Chọn nhiệm vụ</option>{projectTasks.map((task) => <option key={task.id} value={task.id}>{task.code} · {task.title}</option>)}</select>{errors.taskId && <small className="field-error">{errors.taskId}</small>}</label><label>Người thực hiện<select value={timesheet.employeeId} disabled><option value="">Chọn nhiệm vụ trước</option>{projectTasks.filter((task) => task.id === timesheet.taskId).map((task) => <option key={task.assigneeId} value={task.assigneeId}>{task.assigneeName}</option>)}</select>{errors.employeeId && <small className="field-error">{errors.employeeId}</small>}</label><label>Ngày làm việc<input type="date" value={timesheet.workDate} onChange={(event) => setTimesheet({ ...timesheet, workDate: event.target.value })} />{errors.workDate && <small className="field-error">{errors.workDate}</small>}</label><label>Số giờ<input type="number" min="0.5" max="24" step="0.5" value={timesheet.hours} onChange={(event) => setTimesheet({ ...timesheet, hours: event.target.value })} />{errors.hours && <small className="field-error">{errors.hours}</small>}</label><label className="full-width">Nội dung công việc<textarea value={timesheet.note} onChange={(event) => setTimesheet({ ...timesheet, note: event.target.value })} placeholder="Ví dụ: Chuẩn bị phương án giao hàng..." />{errors.note && <small className="field-error">{errors.note}</small>}</label></div>{errors.form && <p className="form-wide-error">{errors.form}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button">Gửi chờ duyệt</button></div></form></div>}
    {modal === "financial" && <div className="modal-backdrop"><form className="modal modal-wide project-form" onSubmit={submitFinancial}><div className="modal-heading"><h2>Liên kết chứng từ tài chính</h2><button type="button" onClick={() => setModal(null)}>×</button></div><p className="modal-description">Chỉ chọn hóa đơn mua hoặc hóa đơn bán đã ghi nhận. Mỗi chứng từ chỉ được phân bổ cho một dự án, nên không thể nhập trùng số tiền.</p><div className="form-grid two-columns"><label>Loại chứng từ<select value={financial.entryType} onChange={(event) => { const entryType = event.target.value as "expense" | "revenue"; const source = overview.financialSources.find((item) => item.entryType === entryType && !overview.financialEntries.some((entry) => entry.sourceDocumentNo === item.documentNo)); setFinancial({ entryType, sourceDocumentNo: source?.documentNo ?? "" }); }}><option value="expense">Chi phí từ hóa đơn mua</option><option value="revenue">Doanh thu từ hóa đơn bán</option></select></label><label>Chứng từ nguồn<select value={financial.sourceDocumentNo} onChange={(event) => setFinancial({ ...financial, sourceDocumentNo: event.target.value })}><option value="">Chọn chứng từ</option>{availableFinancialSources.map((source) => <option key={source.documentNo} value={source.documentNo}>{source.documentNo} · {formatVnd(source.amount)}</option>)}</select>{errors.sourceDocumentNo && <small className="field-error">{errors.sourceDocumentNo}</small>}</label>{financial.sourceDocumentNo && <div className="credit-note full-width">{(() => { const source = availableFinancialSources.find((item) => item.documentNo === financial.sourceDocumentNo); return source ? <><span>{source.description}</span><strong>{formatVnd(source.amount)}</strong><small>Ngày hạch toán: {formatDate(source.postingDate)}</small></> : null; })()}</div>}</div>{errors.form && <p className="form-wide-error">{errors.form}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button" disabled={!financial.sourceDocumentNo}>Liên kết chứng từ</button></div></form></div>}
    {modal === "project" && <div className="modal-backdrop"><form className="modal modal-wide project-form" onSubmit={submitProject}><div className="modal-heading"><h2>{projectForm.id ? "Cập nhật dự án" : "Tạo dự án"}</h2><button type="button" onClick={() => setModal(null)}>×</button></div><div className="form-grid two-columns"><label>Tên dự án<input value={projectForm.name} onChange={(event) => setProjectForm({ ...projectForm, name: event.target.value })} />{errors.name && <small className="field-error">{errors.name}</small>}</label><label>Khách hàng<select value={projectForm.customerId} onChange={(event) => setProjectForm({ ...projectForm, customerId: event.target.value })}><option value="">Chọn khách hàng</option>{overview.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select>{errors.customerId && <small className="field-error">{errors.customerId}</small>}</label><label>Quản lý dự án<select value={projectForm.managerId} onChange={(event) => setProjectForm({ ...projectForm, managerId: event.target.value, teamMemberIds: [...new Set([event.target.value, ...projectForm.teamMemberIds])] })}>{overview.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select>{errors.managerId && <small className="field-error">{errors.managerId}</small>}</label><label>Thành viên team<select multiple value={projectForm.teamMemberIds} onChange={(event) => setProjectForm({ ...projectForm, teamMemberIds: [...event.target.selectedOptions].map((option) => option.value) })}>{overview.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select>{errors.teamMemberIds && <small className="field-error">{errors.teamMemberIds}</small>}</label><label>Bắt đầu<input type="date" value={projectForm.startDate} onChange={(event) => setProjectForm({ ...projectForm, startDate: event.target.value })} /></label><label>Kết thúc<input type="date" value={projectForm.endDate} onChange={(event) => setProjectForm({ ...projectForm, endDate: event.target.value })} />{errors.endDate && <small className="field-error">{errors.endDate}</small>}</label><label>Ngân sách<input type="number" min="1" value={projectForm.budgetAmount || ""} onChange={(event) => setProjectForm({ ...projectForm, budgetAmount: Number(event.target.value) })} />{errors.budgetAmount && <small className="field-error">{errors.budgetAmount}</small>}</label><label>Trạng thái<select value={projectForm.status} onChange={(event) => setProjectForm({ ...projectForm, status: event.target.value as Project["status"] })}><option value="not_started">Chưa bắt đầu</option><option value="in_progress">Đang thực hiện</option><option value="on_hold">Tạm dừng</option></select></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button">Lưu dự án</button></div></form></div>}
    {modal === "task" && <div className="modal-backdrop"><form className="modal modal-wide project-form" onSubmit={submitTask}><div className="modal-heading"><h2>{taskForm.id ? "Cập nhật nhiệm vụ" : "Tạo nhiệm vụ"}</h2><button type="button" onClick={() => setModal(null)}>×</button></div><div className="form-grid two-columns"><label>Tên nhiệm vụ<input value={taskForm.title} onChange={(event) => setTaskForm({ ...taskForm, title: event.target.value })} />{errors.title && <small className="field-error">{errors.title}</small>}</label><label>Người phụ trách<select value={taskForm.assigneeId} onChange={(event) => setTaskForm({ ...taskForm, assigneeId: event.target.value })}>{overview.employees.filter((employee) => selectedProject.teamMemberIds.includes(employee.id)).map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select>{errors.assigneeId && <small className="field-error">{errors.assigneeId}</small>}</label><label>Bắt đầu<input type="date" value={taskForm.startDate} onChange={(event) => setTaskForm({ ...taskForm, startDate: event.target.value })} /></label><label>Hạn hoàn thành<input type="date" value={taskForm.dueDate} onChange={(event) => setTaskForm({ ...taskForm, dueDate: event.target.value })} />{errors.dueDate && <small className="field-error">{errors.dueDate}</small>}</label><label>Ưu tiên<select value={taskForm.priority} onChange={(event) => setTaskForm({ ...taskForm, priority: event.target.value as ProjectTask["priority"] })}><option value="low">Thấp</option><option value="medium">Trung bình</option><option value="high">Cao</option><option value="critical">Khẩn cấp</option></select></label><label className="checkbox-field"><input type="checkbox" checked={taskForm.isMilestone} onChange={(event) => setTaskForm({ ...taskForm, isMilestone: event.target.checked })} /> Milestone dự án</label><label className="full-width">Phụ thuộc nhiệm vụ<select multiple value={taskForm.predecessorIds} onChange={(event) => setTaskForm({ ...taskForm, predecessorIds: [...event.target.selectedOptions].map((option) => option.value) })}>{projectTasks.filter((task) => task.id !== taskForm.id).map((task) => <option key={task.id} value={task.id}>{task.title} · hoàn thành {formatDate(task.dueDate)}</option>)}</select>{errors.predecessorIds && <small className="field-error">{errors.predecessorIds}</small>}</label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button">Lưu nhiệm vụ</button></div></form></div>}
    {modal === "comment" && <div className="modal-backdrop"><form className="modal project-form" onSubmit={submitComment}><div className="modal-heading"><h2>Trao đổi nhiệm vụ</h2><button type="button" onClick={() => setModal(null)}>×</button></div><div className="form-grid"><label>Bình luận<textarea value={comment.message} onChange={(event) => setComment({ ...comment, message: event.target.value })} placeholder="Cập nhật tiến độ hoặc nội dung cần phối hợp..." /></label><label>Tên tệp đính kèm (mô phỏng)<input value={comment.attachmentName} onChange={(event) => setComment({ ...comment, attachmentName: event.target.value })} placeholder="Ví dụ: ke-hoach-giao-hang.pdf" />{errors.message && <small className="field-error">{errors.message}</small>}</label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button">Gửi cập nhật</button></div></form></div>}
  </section>;
}
