import { useCallback, useEffect, useMemo, useState } from "react";
import { DataTable, Column } from "../../components/ui/DataTable";
import { Modal } from "../../components/ui/Modal";
import { StatusBadge } from "../../components/ui/StatusBadge";
import { useToast } from "../../components/ui/Toast";
import { formatVnd } from "../../data/mockData";
import { PosInvoice, PosOverview, PosShift, mockApi } from "../../lib/mockApi";

export function PosPage() {
  const [data, setData] = useState<PosOverview | null>(null); const [profileId, setProfileId] = useState(""); const [openingCash, setOpeningCash] = useState(0); const [closeShift, setCloseShift] = useState<PosShift | null>(null); const [actualCash, setActualCash] = useState(0); const [lines, setLines] = useState<Array<{ itemId: string; quantity: number }>>([]); const [methodId, setMethodId] = useState(""); const [isCheckingOut, setIsCheckingOut] = useState(false); const { showToast } = useToast();
  const load = useCallback(() => { void mockApi.pos.getOverview().then((overview) => { setData(overview); setProfileId((current) => current || overview.profiles[0]?.id || ""); setMethodId((current) => current || overview.paymentMethods[0]?.id || ""); }); }, []); useEffect(() => { load(); }, [load]);
  const profile = data?.profiles.find((item) => item.id === profileId); const activeShift = data?.shifts.find((item) => item.profileId === profileId && item.status === "open"); const cartSubtotal = useMemo(() => lines.reduce((sum, line) => sum + (data?.products.find((product) => product.id === line.itemId)?.sellingPrice ?? 0) * line.quantity, 0), [data, lines]); const cartVat = useMemo(() => lines.reduce((sum, line) => { const product = data?.products.find((item) => item.id === line.itemId); return sum + (product?.sellingPrice ?? 0) * line.quantity * (product?.vatRate ?? 0); }, 0), [data, lines]); const cartTotal = cartSubtotal + cartVat;
  if (!data) return <section className="sales-content"><div className="detail-loading">Đang tải quầy POS...</div></section>;
  const addProduct = (itemId: string) => { if (!itemId) return; setLines((current) => { const existing = current.find((line) => line.itemId === itemId); return existing ? current.map((line) => line.itemId === itemId ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { itemId, quantity: 1 }]; }); };
  const open = async () => { const result = await mockApi.pos.openShift(profileId, openingCash); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.openingCash ?? "Không thể mở ca.", "error"); else { showToast("Đã mở ca thu ngân.", "success"); load(); } };
  const checkout = async () => { if (isCheckingOut) return; setIsCheckingOut(true); const result = await mockApi.pos.checkout({ profileId, paymentMethodId: methodId, lines }); setIsCheckingOut(false); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.lines ?? Object.values(result.errors)[0], "error"); else { showToast(`Đã thanh toán ${result.entity?.receiptNo}.`, "success"); setLines([]); load(); } };
  const close = async () => { if (!closeShift) return; const result = await mockApi.pos.closeShift(closeShift.id, actualCash); if (Object.keys(result.errors).length) showToast(result.errors.form ?? result.errors.actualCash ?? "Không thể đóng ca.", "error"); else { showToast("Đã đóng ca và đối soát tiền mặt.", "success"); setCloseShift(null); load(); } };
  const invoices: Column<PosInvoice>[] = [{ key: "receipt", header: "Hóa đơn", render: (invoice) => <div className="cell-main"><strong>{invoice.receiptNo}</strong><span>{invoice.lines.length} dòng hàng · {invoice.paymentMethodName}</span></div> }, { key: "time", header: "Thời điểm", render: (invoice) => new Date(invoice.postedAt).toLocaleString("vi-VN") }, { key: "total", header: "Tổng thanh toán", className: "text-right", render: (invoice) => <strong>{formatVnd(invoice.totalAmount)}</strong> }];
  return <section className="sales-content pos-page"><div className="content-heading"><div><p className="eyebrow dark">POS – BÁN TẠI QUẦY</p><h2>Quầy thu ngân</h2><p>Mở ca, bán hàng tại quầy, thanh toán và kết ca đối soát.</p></div><div className="pos-profile-select"><label>Quầy POS<select value={profileId} onChange={(event) => { setProfileId(event.target.value); setLines([]); }}>{data.profiles.map((item) => <option value={item.id} key={item.id}>{item.code} · {item.name}</option>)}</select></label></div></div>
    <div className="pos-status"><div><strong>{profile?.storeName}</strong><span>{profile?.name} · Kho xuất: {data.stockBalances.find((balance) => balance.warehouseId === profile?.warehouseId)?.warehouse.name ?? "—"}</span></div>{activeShift ? <div className="pos-shift-open"><StatusBadge status="open" /><span>{activeShift.shiftNo} · Tiền đầu ca {formatVnd(activeShift.openingCash)}</span><button className="secondary-button" onClick={() => { setActualCash(activeShift.expectedCash); setCloseShift(activeShift); }}>Kết ca</button></div> : <div className="pos-open-form"><input type="number" min="0" value={openingCash} onChange={(event) => setOpeningCash(Number(event.target.value))} placeholder="Tiền đầu ca" /><button className="primary-button compact" onClick={() => void open()}>Mở ca</button></div>}</div>
    <div className="pos-grid"><article className="detail-section"><div className="section-heading"><div><h3>Danh mục bán</h3><p>Chỉ hiển thị hàng còn tồn tại kho của quầy.</p></div></div><div className="pos-product-grid">{data.products.filter((product) => product.itemType !== "raw_material" && (!product.trackBatch || data.stockBalances.some((balance) => balance.itemId === product.id && balance.warehouseId === profile?.warehouseId && balance.availableQuantity > 0))).map((product) => <button key={product.id} disabled={!activeShift || isCheckingOut} onClick={() => addProduct(product.id)}><strong>{product.name}</strong><span>{product.sku} · {formatVnd(product.sellingPrice)}</span></button>)}</div></article><article className="detail-section pos-cart"><div className="section-heading"><div><h3>Giỏ hàng</h3><p>{activeShift ? "Tồn kho sẽ được kiểm tra lại khi thanh toán." : "Mở ca để bắt đầu bán hàng."}</p></div></div><div className="pos-cart-lines">{lines.length ? lines.map((line) => { const product = data.products.find((item) => item.id === line.itemId)!; return <div key={line.itemId}><strong>{product.name}</strong><input aria-label={`Số lượng ${product.name}`} disabled={isCheckingOut} type="number" min="1" value={line.quantity} onChange={(event) => setLines((current) => current.map((item) => item.itemId === line.itemId ? { ...item, quantity: Math.max(1, Number(event.target.value)) } : item))} /><span>{formatVnd(product.sellingPrice * line.quantity)}</span><button disabled={isCheckingOut} onClick={() => setLines((current) => current.filter((item) => item.itemId !== line.itemId))}>×</button></div>; }) : <p className="muted-text">Chưa có hàng trong giỏ.</p>}</div><label>Phương thức thanh toán<select disabled={isCheckingOut} value={methodId} onChange={(event) => setMethodId(event.target.value)}>{data.paymentMethods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</select></label><div className="pos-total"><span>Tạm tính</span><strong>{formatVnd(cartSubtotal)}</strong><span>VAT</span><strong>{formatVnd(cartVat)}</strong><b>Thanh toán</b><strong>{formatVnd(cartTotal)}</strong></div><button className="primary-button pos-checkout" disabled={!activeShift || !lines.length || isCheckingOut} onClick={() => void checkout()}>{isCheckingOut ? "Đang thanh toán..." : `Thanh toán ${formatVnd(cartTotal)}`}</button></article></div>
    <div className="content-subheading"><div><h3>Hóa đơn POS gần đây</h3><p>Hóa đơn hoàn tất được ghi nhận theo ca thu ngân.</p></div></div><div className="list-panel"><DataTable columns={invoices} rows={data.invoices} emptyTitle="Chưa có hóa đơn POS" /></div>
    <Modal isOpen={Boolean(closeShift)} title="Kết ca POS" onClose={() => setCloseShift(null)}><div className="crm-form"><div className="payment-balance"><span>Tiền mặt hệ thống kỳ vọng</span><strong>{formatVnd(closeShift?.expectedCash ?? 0)}</strong></div><label>Tiền mặt thực tế<input type="number" min="0" value={actualCash} onChange={(event) => setActualCash(Number(event.target.value))} /></label><div className="modal-actions"><button className="secondary-button" onClick={() => setCloseShift(null)}>Hủy</button><button className="primary-button compact" onClick={() => void close()}>Xác nhận kết ca</button></div></div></Modal>
  </section>;
}
