import { FormEvent, useEffect, useState } from "react";
import { Modal } from "../../components/ui/Modal";
import { formatVnd } from "../../data/mockData";
import { Customer, Delivery, DeliveryDraft, Payment, PaymentDraft, PaymentMethod, SalesDocument, SalesInvoice, StockBatchView, mockApi } from "../../lib/mockApi";

type DeliveryModalProps = { isOpen: boolean; onClose: () => void; order: SalesDocument | null; customer: Customer | null; stockLineIds: string[]; onSaved: (delivery: Delivery) => void };

export function DeliveryFormModal({ isOpen, onClose, order, customer, stockLineIds, onSaved }: DeliveryModalProps) {
  const [draft, setDraft] = useState<DeliveryDraft>({ recipientName: "", recipientPhone: "", deliveryDate: "2026-08-29", lines: [] }); const [batches, setBatches] = useState<StockBatchView[]>([]); const [errors, setErrors] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  const deliveryLines = order?.lines.filter((line) => stockLineIds.includes(line.id) && line.quantity > (line.fulfilledQuantity ?? 0)) ?? [];
  useEffect(() => { if (isOpen && order && customer) { Promise.all([mockApi.inventory.getBatchBalances(), mockApi.inventory.getPickLists()]).then(([batchRows, pickLists]) => { const pickedList = pickLists.find((pickList) => pickList.salesOrderId === order.id && pickList.status === "picked"); setBatches(batchRows); setDraft({ recipientName: customer.name, recipientPhone: customer.phone, deliveryDate: "2026-08-29", lines: order.lines.filter((line) => stockLineIds.includes(line.id) && line.quantity > (line.fulfilledQuantity ?? 0)).map((line) => ({ salesOrderLineId: line.id, deliveredQuantity: Math.max(0, line.quantity - (line.fulfilledQuantity ?? 0)), batchNo: pickedList?.lines.find((pickLine) => pickLine.salesOrderLineId === line.id)?.batchNo ?? "" })) }); }); setErrors({}); } }, [isOpen, order, customer, stockLineIds]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!order) return; setSaving(true); const result = await mockApi.sales.createDelivery(order.id, draft); setSaving(false); if (!result.entity) { setErrors(result.errors); return; } onSaved(result.entity); onClose(); };
  if (!order || !customer) return null;
  return <Modal isOpen={isOpen} onClose={onClose} title={`Tạo phiếu giao · ${order.documentNo}`} wide><form className="crm-form transaction-form" onSubmit={submit}><div className="form-grid two-columns"><label>Người nhận<input value={draft.recipientName} onChange={(event) => setDraft({ ...draft, recipientName: event.target.value })} />{errors.recipientName && <small className="field-error">{errors.recipientName}</small>}</label><label>Số điện thoại người nhận<input value={draft.recipientPhone} onChange={(event) => setDraft({ ...draft, recipientPhone: event.target.value })} />{errors.recipientPhone && <small className="field-error">{errors.recipientPhone}</small>}</label><label>Ngày giao<input type="date" value={draft.deliveryDate} onChange={(event) => setDraft({ ...draft, deliveryDate: event.target.value })} />{errors.deliveryDate && <small className="field-error">{errors.deliveryDate}</small>}</label></div><div className="delivery-lines"><div className="delivery-lines-heading"><strong>Hàng giao</strong><span>Hàng theo lô phải chọn lô còn tồn và được phép xuất.</span></div>{deliveryLines.map((line, index) => { const item = draft.lines[index]; const remaining = line.quantity - (line.fulfilledQuantity ?? 0); const lineBatches = batches.filter((batch) => batch.itemId === line.itemId && batch.warehouseId === order.warehouseId && batch.qualityStatus === "released" && batch.quantityOnHand > 0); return <div className="delivery-line" key={line.id}><div><strong>{line.description}</strong><span>Đặt {line.quantity.toLocaleString("vi-VN")} {line.unit} · còn {remaining.toLocaleString("vi-VN")} {line.unit}</span></div><label>SL giao<input type="number" min="0" max={remaining} value={item?.deliveredQuantity ?? 0} onChange={(event) => setDraft({ ...draft, lines: draft.lines.map((draftLine, lineIndex) => lineIndex === index ? { ...draftLine, deliveredQuantity: Number(event.target.value) } : draftLine) })} /></label><label>Lô hàng<select value={item?.batchNo ?? ""} onChange={(event) => setDraft({ ...draft, lines: draft.lines.map((draftLine, lineIndex) => lineIndex === index ? { ...draftLine, batchNo: event.target.value } : draftLine) })}><option value="">{lineBatches.length ? "Chọn lô hàng" : "Không áp dụng / chưa có lô khả dụng"}</option>{lineBatches.map((batch) => <option key={batch.id} value={batch.batchNo}>{batch.batchNo} · còn {batch.quantityOnHand.toLocaleString("vi-VN")} {batch.item.unit}</option>)}</select></label>{errors[`line-${index}`] && <small className="field-error delivery-line-error">{errors[`line-${index}`]}</small>}</div>; })}</div>{errors.lines && <p className="form-wide-error">{errors.lines}</p>}{errors.form && <p className="form-wide-error">{errors.form}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Hủy</button><button className="primary-button compact" type="submit" disabled={saving}>{saving ? "Đang tạo..." : "Tạo phiếu giao"}</button></div></form></Modal>;
}

export function PaymentFormModal({ isOpen, onClose, invoice, onSaved }: { isOpen: boolean; onClose: () => void; invoice: SalesInvoice | null; onSaved: (payment: Payment) => void }) {
  const [methods, setMethods] = useState<PaymentMethod[]>([]); const [draft, setDraft] = useState<PaymentDraft>({ paymentDate: "2026-08-29", methodId: "", totalAmount: 0 }); const [errors, setErrors] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  useEffect(() => { if (isOpen && invoice) { mockApi.sales.getPaymentMethods().then((items) => { setMethods(items); setDraft({ paymentDate: "2026-08-29", methodId: items[0]?.id ?? "", totalAmount: invoice.balanceAmount }); }); setErrors({}); } }, [isOpen, invoice]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!invoice) return; setSaving(true); const result = await mockApi.sales.recordPayment(invoice.id, draft); setSaving(false); if (!result.entity) { setErrors(result.errors); return; } onSaved(result.entity); onClose(); };
  return <Modal isOpen={isOpen} onClose={onClose} title={invoice ? `Ghi nhận thanh toán · ${invoice.documentNo}` : "Ghi nhận thanh toán"}><form className="crm-form" onSubmit={submit}>{invoice && <div className="payment-balance"><span>Còn phải thu</span><strong>{formatVnd(invoice.balanceAmount)}</strong></div>}<div className="form-grid"><label>Ngày thu tiền<input type="date" value={draft.paymentDate} onChange={(event) => setDraft({ ...draft, paymentDate: event.target.value })} />{errors.paymentDate && <small className="field-error">{errors.paymentDate}</small>}</label><label>Phương thức thanh toán<select value={draft.methodId} onChange={(event) => setDraft({ ...draft, methodId: event.target.value })}>{methods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</select>{errors.methodId && <small className="field-error">{errors.methodId}</small>}</label><label>Số tiền thu<input type="number" min="0" step="1000" value={draft.totalAmount} onChange={(event) => setDraft({ ...draft, totalAmount: Number(event.target.value) })} />{errors.totalAmount && <small className="field-error">{errors.totalAmount}</small>}</label></div>{errors.form && <p className="form-wide-error">{errors.form}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Hủy</button><button className="primary-button compact" type="submit" disabled={saving}>{saving ? "Đang ghi nhận..." : "Ghi nhận thu tiền"}</button></div></form></Modal>;
}
